import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{margin:"auto" ,  width:"30%",textAlign:"center",padding:"20px" , borderRadius:"10px",
           backgroundColor:"teal" , color:"white" , fontSize:"30px" , fontWeight:'bold'}}>
          <Link href="/posts">Posts</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
